accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.IndexView.as_view(), name="login"),
    path('loginrequest/', views.log_in, name="loginrequest"),
    path('logout/', views.log_out, name="logout"),
]

capfinance/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pricing/', include("pricing.urls")),
    path('accounts/', include("accounts.urls")),
    path('api-auth/', include('rest_framework.urls'))
]

pricing/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "pricing"
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('calculator/<int:id_vehicule>', views.calculator, name="calculator"),
    path('calcul/<int:id_vehicule>', views.calcul, name="calcul"),
    path('result/', views.result, name="result"),
    path('checkpricing/', views.CheckPricing.as_view())
]

accounts/models.py
from django.db import models

# Create your models here.

pricing/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True, blank = False)
    description = models.CharField(max_length=255)

    def __str__(self):
        return "{id}-{title}".format(id=self.id, title=self.name)


class Vehicule(models.Model):
    marque = models.CharField(max_length=255, default="marque")
    modele = models.CharField(max_length=255, default="modele")
    description = models.CharField(max_length=255)
    km_initial = models.PositiveIntegerField()
    moteur = models.FloatField(default=0)
    carburant = models.CharField(max_length=10)
    color = models.CharField(max_length=50)
    category = models.ForeignKey(Category, null=True, blank = True, on_delete=models.SET_NULL)
    initial_price = models.FloatField(default=0)


class PricingInfo(models.Model):
    marque = models.CharField(max_length=255, default="marque")
    modele = models.CharField(max_length=255, default="modele")
    price_km_supp = models.FloatField()
    price_rayure = models.FloatField()
    date_modification = models.DateTimeField(default=timezone.now())


class HistoryPricing(models.Model):
    marque = models.CharField(max_length=255, default="marque")
    modele = models.CharField(max_length=255, default="modele")
    price_km_supp = models.FloatField()
    price_rayure = models.FloatField()
    date_modification = models.DateTimeField()

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from django.views import generic


# Create your views here.
class IndexView(generic.TemplateView):
    template_name = "accounts/login.html"


def log_in(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect(reverse('pricing:index'))
    else:
        return HttpResponse("Identifiant ou mot de passe incorrect", status=401)

def log_out(request):
    logout(request)
    return redirect(reverse('accounts:login'))

pricing/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import (
    render,
    get_object_or_404,
    redirect,
    reverse,
)
from django.http import HttpResponse, Http404
from django.views import generic
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import Vehicule, PricingInfo, HistoryPricing
from .serializers import CheckingPriceSerializer

# Create your views here.
class IndexView(generic.ListView):
    template_name = "pricing/index.html"
    context_object_name = "list_vehicules"

    def get_queryset(self):
        return Vehicule.objects.all()

@login_required
def calculator(request, id_vehicule):
    vehicule = get_object_or_404(Vehicule, pk=id_vehicule)
    return render(request, "pricing/calculator.html", {"vehicule": vehicule})

@login_required
def calcul(request, id_vehicule):
    vehicule: Vehicule = get_object_or_404(Vehicule, pk=id_vehicule)
    pricing_info: PricingInfo = get_object_or_404(PricingInfo, modele=vehicule.modele, marque=vehicule.marque)
    total_price = vehicule.initial_price
    price_km_supp = (float(request.POST["km_actuel"]) - vehicule.km_initial) * pricing_info.price_km_supp
    price_rayure_supp = float(request.POST["nb_rayure"]) * pricing_info.price_km_supp
    total_price += price_km_supp + price_rayure_supp
    request.session["total"] = total_price
    return redirect(reverse('pricing:result'))

@login_required
def result(request):
    return render(request, "pricing/result.html", {"total": request.session["total"]})


class CheckPricing(APIView):
    serializer_class = CheckingPriceSerializer

    def post(self, request, format=None):
        data = request.data
        vehicule: Vehicule = get_object_or_404(Vehicule, modele=data.get("modele"), marque=data.get("marque"))
        total_price = vehicule.initial_price
        try:
            pricing = PricingInfo.objects.get(modele=data.get("modele"), marque=data.get("marque"), date_modification__lte=data.get("date"))
        except PricingInfo.DoesNotExist:
            pricing = HistoryPricing.objects.filter(
                modele=data.get("modele"),
                marque=data.get("marque"),
                date_modification__lte=data.get("date")
            ).latest("date_modification")
        price_km_supp = (float(data.get("nb_km")) - vehicule.km_initial) * pricing.price_km_supp
        price_rayure_supp = float(data.get("nb_rayure")) * pricing.price_km_supp
        total_price += price_km_supp + price_rayure_supp
        return Response({"Total": total_price})

accounts/templates/accounts/login.html
<h3>Connexion</h3>

<form action="{% url 'accounts:loginrequest' %}" method="post">
{% csrf_token %}
    <label for="username">Nom d'utilisateur</label>
    <input type="text" name="username" id="username">
    <br><br>

    <label for="password">Mot de passe</label>
    <input type="password" name="password" id="password">
    <br><br>

    <input type="submit" value="Valider">
</form>

pricing/templates/pricing/calculator.html
{% include "pricing/header.html" %}
{% load templates_filter %}

<h1>{{ vehicule.marque }} - {{ vehicule.modele }}</h1>
<ul>
    {% for key, value in vehicule|to_dict|items %}
        <li>{{ key }}  :  {{ value }}</li>
    {% endfor %}
</ul>


<h3>Calculateur de coûts supplémentaires</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'pricing:calcul' vehicule.id %}" method="post">
{% csrf_token %}
    <input type="number" name="km_actuel" id="km_actuel">
    <label for="km_actuel">Km Actuel</label><br><br>

    <input type="number" name="nb_rayure" id="nb_rayure">
    <label for="nb_rayure">Nombre de rayure</label><br><br>

    <input type="submit" value="Valider">
</form>

pricing/templates/pricing/header.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'pricing/style.css' %}">

<div class="header">
  <a href="{% url 'pricing:index' %}" class="logo"><img src="{% static 'pricing/images/logo.png'%}" alt=""></a>
  <h1>Application Capitole Finance-Tofinso</h1>
  <div class="header-right">
    <a class="active" href="{% url 'accounts:logout' %}">Déconnexion</a>
  </div>
</div>

pricing/templates/pricing/index.html
{% include "pricing/header.html" %}

{% if list_vehicules %}
    <ul>
    {% for vehicule in list_vehicules %}
        <li><a href="{% url 'pricing:calculator' vehicule.pk %}">{{ vehicule.marque }} - {{ vehicule.modele }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Aucun véhicule disponible.</p>
{% endif %}

pricing/templates/pricing/result.html
{% include "pricing/header.html" %}

{% if total %}
<h2>Total : {{total}} €</h2>

<a href="{% url 'pricing:index' %}">Retourner sur la liste des véhicules</a>
{% endif %}